public class CheckDatatypes {
   public void methodBoolean(){
    boolean checkBoolean = null;
    system.debug(checkBoolean);
   }
   public void methodInteger(){
    string varFirst='5';
    string varSecond='9';
    string varSum= varFirst+' '+varSecond;
    system.debug(varSum);
   }
   public void stringMethod(){
    string varFirstName= 'Refia';
    string varLastName= 'AKSOY';
    string fullName= varFirstName+' '+varLastName;
    system.debug(fullName);

   }
}