ListDemo2.iterateList();

List<integer> intList2 = new List<integer>{90,15,77,21,15};
system.debug(ListDemo2.add(intList2));

List<string> l2 = new List<string>{'list','set','map','array','methods','constructor'};
ListDemo2.iterateListString(l2);

List<string> strList = new List<string>{'apple','grape','watermelon','strawberry'};
system.debug(ListDemo2.add(strList));

// system.debug(ListDemo2.add(5,5));
