// MethodsDemo2 test = new MethodsDemo2();
// boolean r1 = test.checkContainsA('Christina');
// system.debug('Christina contains a? '+r1);

// MethodsMethodsDemo m = new MethodsMethodsDemo();
// m.printAll();
//0000
//1. print this first
//2. print this second
//1111
//3. print this third
//2222
// Calculator test = new Calculator();
// integer r2 = test.example(9,15);
// system.debug('sum = '+r2);
//calc.add(10,15);//add(integer a, integer b) --> it will automatically recognize from datatype

//calc.add(10.10,15.15);//add(decimal a, decimal b)

// integer x = test.example(10,15,55);
// system.debug('x is ' + x);

// date dt=date.today();
// boolean leapCheck= test.leapYearCheck(dt);
// system.debug(leapCheck);
ArthimaticCalculations test = new ArthimaticCalculations();
system.debug(test.addition(1,3));
system.debug(test.subtraction(10,2));
system.debug(test.multiplication(2,3,4));
system.debug(test.concatString('Soft ',' Innovas' ));




